### ISSUE TITLE
1.7 checklist

### ISSUE THREAD

**Issue by stleary** [stleary/Night-Sky#34]
0. Top priorities:
- [x] ~~Mobile-friendly view~~
Fix visibility of planets text
- [x] ~~Replace the non-numerics with &deg;~~
Fix degree markup: 
Move field touchups to work for cached or server data
Allow manual cache refresh
Jupiter's Moons

~~1. Constellations during the query period. Must be at least 30 degrees above the horizon between astronomical darkness and midnight. Include Messier information?~~ (not supported anymore)

2. Report errors instead of assuming no matching passes.

3. Unit tests - overdue!

4. let user specify altitude, in meters
sun/moon time does not use altitude

~~5. Watermark larger lunar images~~

6. Consider collapsible tables for more page real estate

- [x] 7. ~~Confirm no syntax errors with php 5.2.12~~
~~CONFIRMED. This will have to be done for all releases going forward. 5.2 compatibility will be required.~~

8. Admin settings page, for shortcode defaults

9. collapsible tables?

10. Optional tables?

12
